package pl.jsql.api.enums;

public enum PabblyStatus {

    SUBSCRIPTION_CREATE,
    SUBSCRIPTION_DOWNGRADE,
    SUBSCRIPTION_CANCEL_SCHEDULED,
    SUBSCRIPTION_ACTIVATE,
    SUBSCRIPTION_CANCEL,
    SUBSCRIPTION_TRIAL_EXPIRED,
    SUBSCRIPTION_UPGRADE,
    SUBSCRIPTION_EXPIRE,
    SUBSCRIPTION_RENEW,
    SUBSCRIPTION_DELETE,
    TEST_WEBHOOK_URL,

    SUCCESSFULL_PAYMENT,
    PAYMENT_FAILURE,
    PAYMENT_REFUND,
    GET_CLIENT,
    HOSTED_VERIFY;

}
